#!/bin/bash

echo "🔍 Admin Authorization Debug Test"
echo "================================="

echo "The user balu.in.u@gmail.com has 'admin' role in the database."
echo ""
echo "🧪 To debug the authorization issue:"
echo ""
echo "1. Open browser and login as admin (balu.in.u@gmail.com)"
echo "2. Open DevTools → Console"
echo "3. Run this command to check current user data:"
echo ""
echo "fetch('/api/users/me', {"
echo "  headers: { 'Authorization': 'Bearer ' + localStorage.getItem('authToken') }"
echo "}).then(r => r.json()).then(console.log)"
echo ""
echo "4. Check if the response shows:"
echo "   - user.role: 'admin'"
echo "   - user.userId: 1"
echo "   - user.email: 'balu.in.u@gmail.com'"
echo ""
echo "5. If role is missing or incorrect, the JWT token might be outdated"
echo "   - Try logging out and logging back in"
echo "   - This will generate a new token with correct role information"
echo ""
echo "6. Then test batch creation/assignment again"
echo ""
echo "🔧 Debugging enabled in auth middleware"
echo "Check backend console logs when making admin requests to see:"
echo "- Required roles vs user role"
echo "- Authorization success/failure details"
